// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeWTyp68DYC9JYt_4GXyLOtidh7Yzqtj0',
    appId: '1:324882316402:web:926009a696be73efe796eb',
    messagingSenderId: '324882316402',
    projectId: 'chat-app-9eecc',
    authDomain: 'chat-app-9eecc.firebaseapp.com',
    storageBucket: 'chat-app-9eecc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC7Pq320y9cBTxNgHl-gx_QffrysT8aTo',
    appId: '1:324882316402:android:38ae3157306dcb36e796eb',
    messagingSenderId: '324882316402',
    projectId: 'chat-app-9eecc',
    storageBucket: 'chat-app-9eecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDwhfIRhF_QF6eeXzDa7nSIgg3vaALtmw',
    appId: '1:324882316402:ios:f1c09906d8759844e796eb',
    messagingSenderId: '324882316402',
    projectId: 'chat-app-9eecc',
    storageBucket: 'chat-app-9eecc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDwhfIRhF_QF6eeXzDa7nSIgg3vaALtmw',
    appId: '1:324882316402:ios:f1c09906d8759844e796eb',
    messagingSenderId: '324882316402',
    projectId: 'chat-app-9eecc',
    storageBucket: 'chat-app-9eecc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeWTyp68DYC9JYt_4GXyLOtidh7Yzqtj0',
    appId: '1:324882316402:web:64ee6808c5a3d892e796eb',
    messagingSenderId: '324882316402',
    projectId: 'chat-app-9eecc',
    authDomain: 'chat-app-9eecc.firebaseapp.com',
    storageBucket: 'chat-app-9eecc.appspot.com',
  );

}